version: '3.8'

services:
    postgres:
        image: underwhat/postegresql:latest
        ports:
          - '5432:5432'
        environment:
          - POSTGRES_USER=
          - POSTGRES_PASSWORD=
          - POSTGRES_DB=
        volumes:
          - _pg_data:/underwhat/postegresql

volumes:
  _pg_data:
